"""Batch-generate standalone Do Now handout PDFs — one per lesson-period.

For every teacher tex file (tex/L*_teacher.tex, tex/APStats_*_teacher.tex),
extract every \\bankitem whose label starts with "Do Now" and emit a
standalone tex/{lesson_id}_do_now.tex. Each handout is a one-page
student-facing slip: lesson header, name/period/date line, the Do Now
prompt(s), and generous workspace vspace.

Usage:
    python build_do_now_tex.py                 # emit all
    python build_do_now_tex.py L35_P2 L41_P1   # subset (lesson ids)
    python build_do_now_tex.py --pdf           # also run pdflatex twice
    python build_do_now_tex.py --force         # overwrite hand-authored files

The script refuses to overwrite any tex/*_do_now.tex that doesn't have the
"% GENERATED by build_do_now_tex.py" header (i.e. hand-authored files like
tex/L35_P4_do_now.tex) unless --force is given.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

REPO = Path(__file__).resolve().parent
TEX_DIR = REPO / "tex"
REG_PATH = REPO / "questionbank" / "registry.jsonl"

GEN_HEADER_PREFIX = "% GENERATED by build_do_now_tex.py"


# ── Brace-balanced extractor (from supabase/seed_lesson_phases.py) ──────────

def find_brace_group(s: str, start: int) -> tuple[str, int]:
    """Given s[start] == '{', return (inside_content, index_after_closing_brace)."""
    assert s[start] == "{", f"expected {{, got {s[start]!r} at {start}"
    depth = 0
    i = start
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return s[start + 1:i], i + 1
        i += 1
    raise ValueError(f"unterminated brace starting at {start}")


# ── Lesson id / header parsing ──────────────────────────────────────────────

def parse_filename(tex_path: Path) -> tuple[str, str, str, str] | None:
    """Return (lesson_id, header_lesson, period_n, kind) or None.

    L35_P2_teacher.tex         -> ('L35_P2', 'Lesson 3-5', '2', 'L')
    APStats_6-4_P1_teacher.tex -> ('APStats_6-4_P1', 'APStats 6-4', '1', 'AP')
    """
    name = tex_path.stem  # e.g. L35_P2_teacher
    m = re.match(r"(L(\d)(\d)_P(\d+))_teacher$", name)
    if m:
        return m.group(1), f"Lesson {m.group(2)}-{m.group(3)}", m.group(4), "L"
    m = re.match(r"(APStats_(\d+)-(\d+)_P(\d+))_teacher$", name)
    if m:
        return (
            m.group(1),
            f"APStats {m.group(2)}-{m.group(3)}",
            m.group(4),
            "AP",
        )
    return None


# ── Bank-id detection inside a Do Now label ─────────────────────────────────
# The label always comes after "Do Now" and may contain a parenthesized bank
# id like "(3-5-savvas-q13)" or "(4-1-savvas-model-discuss-lesson-4-1-launch)".

RE_ID_IN_PARENS = re.compile(r"\(([0-9a-zA-Z][\w\-]+)\)")


def extract_bank_id(label: str, known_ids: set[str]) -> str | None:
    for m in RE_ID_IN_PARENS.finditer(label):
        cand = m.group(1)
        if cand in known_ids:
            return cand
    return None


# ── Do Now bankitem extraction ──────────────────────────────────────────────

def extract_do_nows(tex: str) -> list[tuple[str, str]]:
    """Return (label, body) for every \\bankitem whose label begins with
    'Do Now', in file order."""
    items: list[tuple[str, str]] = []
    for m in re.finditer(r"\\bankitem\s*\{", tex):
        label_start = m.end() - 1  # '{'
        try:
            label, after_label = find_brace_group(tex, label_start)
        except ValueError:
            continue
        body_start = tex.find("{", after_label)
        if body_start == -1:
            continue
        try:
            body, _ = find_brace_group(tex, body_start)
        except ValueError:
            continue
        # Normalize whitespace for prefix check only; keep original label/body
        # for output so LaTeX rendering matches what the teacher already sees.
        clean = label.strip()
        if clean.lower().startswith("do now"):
            items.append((label, body))
    return items


# ── Registry loader ─────────────────────────────────────────────────────────

def load_registry() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for line in REG_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue
        rid = r.get("id")
        if rid:
            out[rid] = r
    return out


# ── Label cleanup for display ───────────────────────────────────────────────
# The raw label "Do Now \#1 --- Error Analysis (q14) (6-3-savvas-q14)" should
# render on the handout without the trailing bank-id parenthetical. We strip
# the rightmost (bank-id) group if it matches a known registry id.

def pretty_label(raw: str, known_ids: set[str]) -> str:
    # strip any (bank-id) parens that map to a real registry id
    def _sub(m):
        return "" if m.group(1) in known_ids else m.group(0)
    out = RE_ID_IN_PARENS.sub(_sub, raw)
    return re.sub(r"\s+", " ", out).strip().rstrip("-").strip()


# ── Tex emitter ─────────────────────────────────────────────────────────────

TEMPLATE = r"""% GENERATED by build_do_now_tex.py on {today} --- do not hand-edit; regenerate instead.
\documentclass[11pt]{{article}}
\usepackage{{preamble}}
{extra_preamble}

\begin{{document}}

\packetheading{{{header}}}{{{subtitle}}}

\vspace{{0.25em}}
\noindent\textbf{{Name:}}\ \rule{{2in}}{{0.4pt}}\quad
\textbf{{Period:}}\ \rule{{0.5in}}{{0.4pt}}\quad
\textbf{{Date:}}\ \rule{{1in}}{{0.4pt}}
\vspace{{0.5em}}

{body}
\end{{document}}
"""


def render_bankitem(label: str, body: str, vspace: str) -> str:
    if body.strip():
        body_block = body.rstrip() + "\n"
    else:
        body_block = "\\vspace{1em}\n"
    return (
        f"\\bankitem{{{label}}}{{%\n"
        f"{body_block}"
        f"}}{{}}\n"
        f"\\vspace{{{vspace}}}\n"
    )


RE_MACRO_USE = re.compile(r"\\([A-Za-z@]+)")


def find_local_macro_definition(tex: str, name: str) -> str | None:
    pat = re.compile(
        rf"\\(?:newcommand|renewcommand|providecommand)\s*\{{\\{re.escape(name)}\}}"
    )
    for m in pat.finditer(tex):
        cur = m.end()
        while cur < len(tex) and tex[cur].isspace():
            cur += 1
        while cur < len(tex) and tex[cur] == "[":
            end = tex.find("]", cur)
            if end == -1:
                break
            cur = end + 1
            while cur < len(tex) and tex[cur].isspace():
                cur += 1
        if cur >= len(tex) or tex[cur] != "{":
            continue
        try:
            _, end = find_brace_group(tex, cur)
        except ValueError:
            continue
        return tex[m.start():end]
    return None


def collect_local_macros(tex: str, body: str) -> list[str]:
    defs: list[str] = []
    seen: set[str] = set()
    for name in sorted(set(RE_MACRO_USE.findall(body))):
        if name in seen:
            continue
        definition = find_local_macro_definition(tex, name)
        if definition:
            defs.append(definition)
            seen.add(name)
    return defs


def build_tex_for_lesson(
    lesson_id: str,
    header_lesson: str,
    period_n: str,
    do_nows: list[tuple[str, str]],
    registry: dict[str, dict],
    source_tex: str,
) -> str | None:
    """Return tex content, or None to skip (no Do Nows)."""
    if not do_nows:
        return None
    known_ids = set(registry.keys())

    # Adjust vspace based on number of items so a 1-item handout gets generous
    # room and a 3-item handout still fits (roughly) on one page.
    if len(do_nows) >= 3:
        vspace = "1.2in"
    elif len(do_nows) == 2:
        vspace = "1.8in"
    else:
        vspace = "2.5in"

    body_parts: list[str] = []
    extra_preamble_defs: list[str] = []
    seen_macro_defs: set[str] = set()
    for raw_label, fallback_body in do_nows:
        bid = extract_bank_id(raw_label, known_ids)
        display = pretty_label(raw_label, known_ids) or "Do Now"
        if bid:
            body = registry[bid].get("prompt", "").strip()
        else:
            body = fallback_body.strip()
            for definition in collect_local_macros(source_tex, body):
                if definition not in seen_macro_defs:
                    extra_preamble_defs.append(definition)
                    seen_macro_defs.add(definition)
        body_parts.append(render_bankitem(display, body, vspace))

    header = f"{header_lesson} \\textperiodcentered\\ Period {period_n} \\textperiodcentered\\ Do Now"
    subtitle = lesson_id.replace("_", " ")
    extra_preamble = ""
    if extra_preamble_defs:
        extra_preamble = "\n" + "\n\n".join(extra_preamble_defs)
    return TEMPLATE.format(
        today=date.today().isoformat(),
        header=header,
        subtitle=subtitle,
        extra_preamble=extra_preamble,
        body="\n".join(body_parts),
    )


# ── File-overwrite safety check ─────────────────────────────────────────────

def is_generated(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8") as f:
            first = f.readline()
    except OSError:
        return False
    return first.startswith(GEN_HEADER_PREFIX)


# ── pdflatex step ───────────────────────────────────────────────────────────

def run_pdflatex(tex_file: Path) -> bool:
    cmd = [
        "pdflatex",
        "--interaction=nonstopmode",
        "--miktex-enable-installer",
        f"-output-directory={tex_file.parent}",
        str(tex_file),
    ]
    ok = True
    for _ in range(2):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        except (FileNotFoundError, subprocess.TimeoutExpired) as e:
            print(f"  pdflatex failed for {tex_file.name}: {e}")
            return False
        if r.returncode != 0:
            ok = False
    return ok


# ── Main ────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("lessons", nargs="*",
                    help="optional subset of lesson ids (e.g. L35_P2 L41_P1)")
    ap.add_argument("--pdf", action="store_true",
                    help="also run pdflatex (twice) on each emitted tex")
    ap.add_argument("--force", action="store_true",
                    help="overwrite hand-authored *_do_now.tex files too")
    args = ap.parse_args()

    registry = load_registry()

    teacher_files = sorted(TEX_DIR.glob("L*_teacher.tex")) + sorted(
        TEX_DIR.glob("APStats_*_teacher.tex"))
    teacher_files = [f for f in teacher_files if "_regen" not in f.stem]

    wanted: set[str] | None = set(args.lessons) if args.lessons else None

    emitted = 0
    skipped_empty: list[str] = []
    skipped_protected: list[str] = []
    pdf_ok = 0
    pdf_fail: list[str] = []

    for tp in teacher_files:
        parsed = parse_filename(tp)
        if not parsed:
            continue
        lesson_id, header_lesson, period_n, _kind = parsed
        if wanted is not None and lesson_id not in wanted:
            continue

        tex = tp.read_text(encoding="utf-8")
        do_nows = extract_do_nows(tex)
        if not do_nows:
            skipped_empty.append(lesson_id)
            continue

        out_tex = build_tex_for_lesson(lesson_id, header_lesson, period_n,
                                       do_nows, registry, tex)
        if out_tex is None:
            skipped_empty.append(lesson_id)
            continue

        dest = TEX_DIR / f"{lesson_id}_do_now.tex"
        if dest.exists() and not is_generated(dest) and not args.force:
            print(f"  SKIP (hand-authored): {dest.name}  (pass --force to overwrite)")
            skipped_protected.append(lesson_id)
            continue

        dest.write_text(out_tex, encoding="utf-8")
        print(f"  wrote {dest.name}  ({len(do_nows)} Do Now block{'s' if len(do_nows) > 1 else ''})")
        emitted += 1

        if args.pdf:
            if run_pdflatex(dest):
                pdf_ok += 1
            else:
                pdf_fail.append(lesson_id)

    print()
    print(f"emitted:            {emitted}")
    if skipped_empty:
        print(f"skipped (no Do Now): {len(skipped_empty)}  ({', '.join(skipped_empty)})")
    if skipped_protected:
        print(f"skipped (hand-authored): {len(skipped_protected)}  ({', '.join(skipped_protected)})")
    if args.pdf:
        print(f"pdflatex ok:        {pdf_ok}")
        if pdf_fail:
            print(f"pdflatex failed:    {len(pdf_fail)}  ({', '.join(pdf_fail)})")
    return 0 if not pdf_fail else 1


if __name__ == "__main__":
    raise SystemExit(main())
