"""
classifications_data.py

Hand-authored classification judgments for each of the 137 ABSENT rows
(has_visual=True, image empty/None), keyed by registry_line (1-based line
number in questionbank/registry.jsonl) to disambiguate duplicate ids.

Each entry: (importance, importance_rationale, recoverability, recoverability_rationale, flags)

importance in {essential, supporting, decorative}
recoverability in {tikz_regenerable, source_pdf_required, irreplaceable_photo}
flags: list of strings from the fixed vocabulary in the WS2 spec.

This file is read-only input to build_classification.py. It does not read or
write questionbank/ itself.
"""

CLASSIFICATIONS = {
    # ---------------- 4-3 (8 rows) ----------------
    43: ("supporting",
         "The domain/asymptote reasoning follows from the stated equation y=x+2; the graph illustrates but does not gate the answer.",
         "tikz_regenerable",
         "y=x+2 is a stated linear equation, trivially plottable.",
         []),
    49: ("supporting",
         "Both packaging shapes are fully dimensioned in text (edge 2x for the prism, radius/height x and 2x for the cylinder) and all algebra is worked out; the photo only illustrates the two shapes.",
         "tikz_regenerable",
         "The prism and cylinder are labeled geometric solids with all dimensions given in terms of x.",
         []),
    79: ("essential",
         "'Find and simplify the ratio of the volume of Figure A to the volume of Figure B' gives no dimensions or expressions for either figure anywhere in the prompt text.",
         "source_pdf_required",
         "Figure A/Figure B dimensions exist only in the source figure; the Savvas SE/TE PDF is needed to recover them.",
         ["needs_teacher_confirmation"]),
    80: ("essential",
         "The cylindrical structures A and B are described only as 'shown'; no radius or height values appear in the prompt text.",
         "source_pdf_required",
         "Cylinder A/B dimensions live only in the figure, not restated in text.",
         ["needs_teacher_confirmation"]),
    81: ("decorative",
         "The carnival-game photo's every dimension (3x bottom, x+1 side, target x by 1/2x) is already transcribed into the placeholder text, so the photo is scene-setting only.",
         "irreplaceable_photo",
         "Depicts a child tossing a beanbag at a real carnival booth -- a real-world scene, not a redrawable technical figure.",
         ["photo_solvable_from_text"]),
    82: ("essential",
         "The parallelogram's height is described only as 'shown' in the figure; no numeric or symbolic height value appears in the prompt text.",
         "source_pdf_required",
         "The height value needed to find the base length exists only in the original figure.",
         ["needs_teacher_confirmation"]),
    93: ("supporting",
         "This is a concept-summary reference table; all worked examples and practice items are fully embedded as text/TABLE content.",
         "tikz_regenerable",
         "Content is a TABLE...END_TABLE structure fully transcribed in the prompt.",
         []),
    898: ("supporting",
          "This DOK-1 scaffold ('Write the rational expression for the probability of winning') is a build-up step tied to the same carnival-box diagram as 4-3-savvas-q36, whose dimensions are known.",
          "tikz_regenerable",
          "Reuses the same labeled box (3x, x+1, x, 1/2x) already regenerable for q36.",
          ["needs_teacher_confirmation"]),

    # ---------------- 5-1 (21 rows) ----------------
    113: ("supporting",
          "The graph plots the stated function y=x^2 (and later y=x^3); part B asks students to use the graph to reason about a value on that stated curve.",
          "tikz_regenerable",
          "y=x^2 and y=x^3 are simple stated equations.",
          []),
    114: ("supporting",
          "Duplicate occurrence of the y=x^2 / y=x^3 Explore & Reason launch; same stated-equation reasoning task.",
          "tikz_regenerable",
          "y=x^2 and y=x^3 are simple stated equations.",
          []),
    117: ("supporting",
          "The algebra fully solves 2x^5=64 and 3x^4=1875 in text; the graph is shown afterward only to confirm the number of real solutions.",
          "tikz_regenerable",
          "Graphs plot the already-solved equations, fully known from text.",
          []),
    118: ("decorative",
          "The fountain's volume (729 cm^3) is captured in the image label and reused directly in the worked algebra; the photo is scene-setting for a garden fountain.",
          "irreplaceable_photo",
          "A real garden water fountain scene, not a redrawable technical figure.",
          ["photo_solvable_from_text"]),
    119: ("supporting",
          "The graph of f(x)=x^3-125 is used to confirm the single real cube root already found algebraically in text.",
          "tikz_regenerable",
          "f(x)=x^3-125 is a stated function.",
          []),
    120: ("decorative",
          "The tornado's wind speed (100 mph) appears in the image label and is used directly in the algebra that follows; the tornado photo is context only.",
          "irreplaceable_photo",
          "A tornado photo is a real-world scene that cannot be redrawn as a figure.",
          ["photo_solvable_from_text"]),
    145: ("decorative",
          "The sphere volume (4,186 2/3 in.^3) needed to solve for r is stated in the placeholder label itself.",
          "irreplaceable_photo",
          "Inflated spheres above a crowd is a real-world event photo.",
          ["photo_solvable_from_text"]),
    146: ("essential",
          "This is an error-analysis item ('Describe and correct the error a student made') whose specific incorrect student work is not reproduced anywhere in the prompt text.",
          "source_pdf_required",
          "The wrong student work exists only in the source figure.",
          ["needs_teacher_confirmation"]),
    169: ("decorative",
          "The smaller cube's volume (85 in.^3) needed to solve is stated in the image label.",
          "irreplaceable_photo",
          "Photo of two chocolate boxes is a real-world product scene.",
          ["photo_solvable_from_text"]),
    170: ("decorative",
          "The ball's volume (approx 4.19 m^3) needed to solve for r is stated in the placeholder label.",
          "irreplaceable_photo",
          "A person inside a water-walking ball is a real-world scene.",
          ["photo_solvable_from_text"]),
    171: ("decorative",
          "The box's volume (3,456 in.^3) and the height=width, length=2xwidth relationships are all stated in the main prompt text, not just the image.",
          "tikz_regenerable",
          "Despite being tagged photo, this is a labeled rectangular prism (depth x, height x, width 2x) -- a redrawable geometric solid, not a true photographic subject.",
          []),
    174: ("supporting",
          "All five expressions to classify Yes/No are fully given in the TABLE content.",
          "tikz_regenerable",
          "Table content is entirely text/TABLE-based.",
          []),
    176: ("decorative",
          "The container's volume (169.65 ft^3) and the height=diameter relationship are both stated in text/placeholder.",
          "irreplaceable_photo",
          "A milk processing facility photo is a real-world industrial scene.",
          ["needs_teacher_confirmation"]),
    178: ("decorative",
          "Duplicate occurrence: the sphere volume (4,186 2/3 in.^3) needed to solve for r is stated in the image label.",
          "irreplaceable_photo",
          "Inflated spheres above a crowd is a real-world event photo.",
          ["photo_solvable_from_text"]),
    201: ("decorative",
          "Duplicate occurrence: the smaller cube's volume (85 in.^3) needed to solve is stated in the image label.",
          "irreplaceable_photo",
          "Photo of two chocolate boxes is a real-world product scene.",
          ["photo_solvable_from_text"]),
    202: ("decorative",
          "Duplicate occurrence: the ball's volume (approx 4.19 m^3) needed to solve for r is stated in the image label.",
          "irreplaceable_photo",
          "A person inside a water-walking ball is a real-world scene.",
          ["photo_solvable_from_text"]),
    203: ("supporting",
          "Same gift-box scenario as 5-1-savvas-q45 (volume 3,456 in.^3, height=width, length=2xwidth all stated in text), but rendered as an abstract graph/diagram rather than a real-world photo.",
          "tikz_regenerable",
          "A labeled rectangular prism fully specified by the stated relationships.",
          []),
    206: ("supporting",
          "Duplicate occurrence: all five expressions to classify Yes/No are fully given in the TABLE content.",
          "tikz_regenerable",
          "Table content is entirely text/TABLE-based.",
          []),
    208: ("decorative",
          "Duplicate occurrence: the container's volume (169.65 ft^3) and height=diameter relationship are both stated in text/image label.",
          "irreplaceable_photo",
          "A milk processing facility photo is a real-world industrial scene.",
          ["needs_teacher_confirmation"]),
    214: ("supporting",
          "This concept-summary table and its Do You Know How practice items (including the snow-globe cube problem, whose dimensions are all stated in prose) are fully self-contained.",
          "tikz_regenerable",
          "Table/TABLE content plus text-only word problems.",
          []),
    241: ("supporting",
          "The two cube packages' relationship (edge 3 in. greater, surface area 384 in.^2) is fully stated in text and solved algebraically; the graph illustrates the same known cubes.",
          "tikz_regenerable",
          "Labeled cubes with dimensions x and x+3, fully specified in text.",
          []),

    # ---------------- 5-4 (19 rows) ----------------
    247: ("supporting",
          "The radical equation is solved algebraically in full; the graph of y=sqrt(x+5)-1 and y=3 is shown only to confirm the intersection at (11,3) already found.",
          "tikz_regenerable",
          "Both functions are stated equations.",
          []),
    248: ("decorative",
          "The governing equation x=sqrt(y-220)/0.010583 is transcribed in the placeholder text and reused directly in the algebra; the Golden Gate Bridge photo is scenic context.",
          "irreplaceable_photo",
          "A real landmark bridge photo cannot be redrawn as a figure.",
          ["photo_solvable_from_text"]),
    249: ("supporting",
          "Both the extraneous-solution algebra and the explanation are complete in text; the two graphs shown merely illustrate the already-derived intersection points.",
          "tikz_regenerable",
          "All four plotted functions are stated equations.",
          []),
    251: ("supporting",
          "The equation sqrt(x+9)-sqrt(2x)=3 is solved fully algebraically with both candidate solutions checked in text; the graph merely confirms a single intersection at x=0.",
          "tikz_regenerable",
          "Both graphed functions are stated equations.",
          []),
    252: ("decorative",
          "The BSA threshold (<1.9) and height (160 cm) needed to solve are given in the placeholder label and used directly in the algebra.",
          "irreplaceable_photo",
          "A doctor looking at a tablet is a real-world professional scene.",
          ["photo_solvable_from_text"]),
    276: ("essential",
          "'Find the point of intersection of the two graphs' gives no equations for either curve anywhere in the prompt text.",
          "source_pdf_required",
          "The two curves and their intersection point exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    297: ("decorative",
          "The athlete's height (165 cm) and BSA threshold (<2.0) needed to solve are given in the image labels.",
          "irreplaceable_photo",
          "A runner finishing a race is a real-world sports photo.",
          ["photo_solvable_from_text"]),
    298: ("decorative",
          "The governing formula ('Vehicle's speed is 15.9 sqrt(df)') is transcribed in the placeholder and is all that's needed to rewrite for d.",
          "irreplaceable_photo",
          "A car leaving skid marks on a road is a real-world scene.",
          ["photo_solvable_from_text"]),
    301: ("decorative",
          "The visibility value (v=67.1 miles) needed to solve is given in the image label; the formula v=1.225 sqrt(a) is already in the main text.",
          "irreplaceable_photo",
          "A hang glider photo is a real-world scene.",
          ["photo_solvable_from_text"]),
    302: ("supporting",
          "All row values (known and to-solve-for) are given directly in the TABLE content.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    304: ("decorative",
          "Earth's radius (6,371,000 m) needed for Part B is given in the placeholder; the escape-velocity formula and G are already in the main text.",
          "irreplaceable_photo",
          "Earth with a rocket trajectory is an illustrative real-world-styled scene.",
          ["needs_teacher_confirmation"]),
    307: ("essential",
          "Duplicate occurrence: 'Find the point of intersection of the two graphs' gives no equations for either curve anywhere in the prompt text.",
          "source_pdf_required",
          "The two curves and their intersection point exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    326: ("decorative",
          "Duplicate occurrence: the athlete's height (165 cm) and BSA threshold (<2.0) needed to solve are given in the image labels.",
          "irreplaceable_photo",
          "A runner/athlete photo is a real-world sports photo.",
          ["photo_solvable_from_text"]),
    327: ("decorative",
          "Duplicate occurrence: the governing formula is transcribed in the placeholder and is all that's needed to rewrite for d.",
          "irreplaceable_photo",
          "Car skid marks on a road is a real-world scene.",
          ["photo_solvable_from_text"]),
    330: ("decorative",
          "Duplicate occurrence: the visibility value needed to solve is given in the image label; the formula is already in the main text.",
          "irreplaceable_photo",
          "A hang glider photo is a real-world scene.",
          ["photo_solvable_from_text"]),
    331: ("supporting",
          "Duplicate occurrence: all row values (known and to-solve-for) are given directly in the TABLE content.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    333: ("decorative",
          "Duplicate occurrence: Earth's radius needed for Part B is given in the placeholder; the escape-velocity formula and G are already in the main text.",
          "irreplaceable_photo",
          "Earth with a rocket trajectory is an illustrative real-world-styled scene.",
          ["needs_teacher_confirmation"]),
    346: ("supporting",
          "The four-step solving process (2 sqrt(x+3)-x=0 through eliminating extraneous solutions) is worked fully in the ALGEBRA column; the GRAPH column repeats a stated equation.",
          "tikz_regenerable",
          "Graphs the stated equation 2 sqrt(x+3)=x.",
          []),
    347: ("supporting",
          "Same four-step solving process plus Do You Understand/Know How practice items, all fully worked or self-contained in text.",
          "tikz_regenerable",
          "Graphs the stated equation from Step 3; remaining items are text-only.",
          []),

    # ---------------- 5-5 (13 rows) ----------------
    377: ("decorative",
          "The per-pet price ($25) needed to define the revenue function is given only in the sign within the image, captured there as text; materials cost and fixed costs are in the main prompt.",
          "irreplaceable_photo",
          "A groomer with a dog and a real storefront sign is a real-world scene.",
          ["photo_solvable_from_text"]),
    378: ("decorative",
          "Duplicate occurrence: the per-pet price ($25) needed to define the revenue function is captured in the sign within the image.",
          "irreplaceable_photo",
          "A groomer with a dog and a real storefront sign is a real-world scene.",
          ["photo_solvable_from_text"]),
    380: ("decorative",
          "d(x), c(x), and the profit relationship are all defined algebraically in text; the image is a metaphorical icon chart (phone x demand - parts) adding no new data.",
          "irreplaceable_photo",
          "An icon/photo montage rather than a labeled technical diagram.",
          ["photo_solvable_from_text"]),
    382: ("supporting",
          "f(x)=x^2 and g(x)=x+1 are stated, and the composition table for f(g(x)) is fully worked in text/TABLE.",
          "tikz_regenerable",
          "TABLE content is fully specified.",
          []),
    384: ("decorative",
          "Both discount amounts ($5, 10%) shown on the coupons are already stated in the main text's function definitions f(x)=x-5 and g(x)=0.9x.",
          "irreplaceable_photo",
          "A smartphone coupon screen is a real-world product photo.",
          ["photo_solvable_from_text"]),
    409: ("decorative",
          "Both offers ($50 rebate, 10% discount) shown as stickers are restated in the image labels, and the $400 price is in the main text.",
          "irreplaceable_photo",
          "Snowboards on display is a real-world retail photo.",
          ["photo_solvable_from_text"]),
    411: ("decorative",
          "Both discounts ($5 off $20+, additional 15% off) shown in the ad are also referenced directly in parts a-c of the main text.",
          "irreplaceable_photo",
          "A drum set with a promotional sign is a real-world retail photo.",
          ["photo_solvable_from_text"]),
    415: ("supporting",
          "The Celsius-Fahrenheit-Kelvin conversion relationships needed for Parts A/B are already spelled out in the main prompt text ('32 less...multiplied by five-ninths', 'plus 273'); the triple-thermometer diagram illustrates the same correspondence.",
          "tikz_regenerable",
          "Three vertical scales with fully specified markings and one dashed correspondence line -- a drawable reference diagram.",
          []),
    433: ("decorative",
          "Duplicate occurrence: both offers ($50 rebate, 10% discount) shown as stickers are restated in the image labels, and the $400 price is in the main text.",
          "irreplaceable_photo",
          "Snowboards on display is a real-world retail photo.",
          ["photo_solvable_from_text"]),
    435: ("decorative",
          "Duplicate occurrence: both discounts shown in the ad are also referenced directly in parts a-c of the main text.",
          "irreplaceable_photo",
          "A drum set with a promotional sign is a real-world retail photo.",
          ["photo_solvable_from_text"]),
    439: ("supporting",
          "Same temperature-conversion item as 5-5-savvas-q36 with all relationships already stated in text, rendered here as an abstract graph placeholder rather than the thermometer photo.",
          "tikz_regenerable",
          "A drawable reference diagram/graph, all specs given in text.",
          []),
    448: ("supporting",
          "This concept-summary table (add/subtract, multiply/divide, compose functions) is fully worked with algebra, words, and numbers in the TABLE content.",
          "tikz_regenerable",
          "Table content is entirely text/TABLE-based.",
          []),
    449: ("supporting",
          "Same concept-summary table plus Do You Understand/Know How practice items, all self-contained in text.",
          "tikz_regenerable",
          "Table content is entirely text/TABLE-based.",
          []),

    # ---------------- 6-3 (17 rows) ----------------
    473: ("supporting",
          "Both Taylor's and Chen's full methods and the amplitude/magnitude table are transcribed completely in text; the item asks students to critique reasoning already shown.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    474: ("supporting",
          "Duplicate occurrence of the Taylor/Chen earthquake-magnitude critique, fully transcribed in text.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    475: ("supporting",
          "The logarithm definition (2^x=8 solved via log_2 8=x) is explained fully in the main text; the diagram is a side callout analogy to division as the inverse of multiplication.",
          "tikz_regenerable",
          "A simple text callout box, easily reproduced.",
          []),
    477: ("decorative",
          "Pure numeric evaluation of log_5 125, log_(1/4) 16, log_3 0, log_2 2^8 -- no image content is actually needed; visual_type is recorded as none despite has_visual=True.",
          "tikz_regenerable",
          "No asset is needed for this text-only computation item.",
          ["has_visual_true_but_visual_type_none", "needs_teacher_confirmation"]),
    478: ("supporting",
          "log 900, ln e, and ln(-1.87) are all evaluated with full reasoning in text; the calculator-screen image reproduces values already stated.",
          "tikz_regenerable",
          "A simple calculator-screen mockup of values already known from text.",
          []),
    479: ("supporting",
          "Both equations (25=10^(x-1) and ln(2x+3)=4) are solved fully in text; the callouts are brief captions ('Convert to logarithmic/exponential form').",
          "tikz_regenerable",
          "Text callouts, easily reproduced.",
          []),
    480: ("supporting",
          "The seismic-energy problem is solved fully with the given formula and value (4.2x10^20 J) in text; the magnitude-category scale image is supplementary context, not required to solve.",
          "tikz_regenerable",
          "A categorical reference scale that is fully describable and redrawable.",
          []),
    483: ("decorative",
          "Pure numeric evaluation (log_3(1/81), log_7(-7), log_5 5^9) -- no image content is needed; visual_type recorded as none despite has_visual=True.",
          "tikz_regenerable",
          "No asset needed for this text-only computation item.",
          ["has_visual_true_but_visual_type_none", "needs_teacher_confirmation"]),
    484: ("decorative",
          "Pure numeric evaluation (log 321, ln 1215, log 0.17) -- no image content is needed; visual_type recorded as none despite has_visual=True.",
          "tikz_regenerable",
          "No asset needed for this text-only computation item.",
          ["has_visual_true_but_visual_type_none", "needs_teacher_confirmation"]),
    485: ("decorative",
          "Pure equation solving (log(3x-2)=2, e^(x+2)=8) -- no image content is needed; visual_type recorded as none despite has_visual=True.",
          "tikz_regenerable",
          "No asset needed for this text-only computation item.",
          ["has_visual_true_but_visual_type_none", "needs_teacher_confirmation"]),
    504: ("supporting",
          "Both accounts' year-by-year balances are given completely in the TABLE content for students to model.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    506: ("supporting",
          "The graph plots the stated function y=3^x and is used to estimate log_3 50 -- a graph of a stated function used to reason about that function.",
          "tikz_regenerable",
          "y=3^x is a simple stated exponential.",
          []),
    542: ("decorative",
          "The magnitude-4 wall-cracking threshold needed for part (c) is captured in the image's callout text ('At a richter magnitude of 4 and above...'); the formula and other givens are in the main text.",
          "irreplaceable_photo",
          "A cracked-wall photo with an overlay is a real-world scene.",
          ["photo_solvable_from_text"]),
    544: ("supporting",
          "The five answer choices are fully given in the TABLE content for this SAT/ACT item.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    545: ("supporting",
          "Exponential/logarithmic form definitions (a^b=c, log_a c=b) are given fully in text; the callout is a brief caption about the term 'argument'.",
          "tikz_regenerable",
          "Text-based concept box.",
          []),
    549: ("supporting",
          "Exponential and logarithmic forms with a worked numeric example (3^4=81) are fully given in the TABLE content.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    550: ("supporting",
          "Same exponential/logarithmic forms TABLE plus Do You Understand/Know How practice items, all self-contained in text.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),

    # ---------------- 6-4 (23 rows) ----------------
    573: ("essential",
          "'Compare the graphs...Which two graphs represent the inverse of each other?' gives no equations for any of the three graphs in the prompt text.",
          "source_pdf_required",
          "The three functions being compared exist only in the original figures.",
          ["needs_teacher_confirmation"]),
    574: ("essential",
          "Duplicate occurrence (single-graph variant): no equations for the compared graphs appear in the prompt text.",
          "source_pdf_required",
          "The functions being compared exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    575: ("supporting",
          "Domain, range, x-intercept, asymptote, and end behavior of g(x)=log_2 x are all listed explicitly in text; the graph illustrates that stated function.",
          "tikz_regenerable",
          "g(x)=log_2 x is a stated function with tabulated points also given.",
          []),
    576: ("supporting",
          "The 3-unit left shift of g(x)=log_2(x+3) from f(x)=log_2 x is fully derived algebraically in text; the graph illustrates the stated transformation.",
          "tikz_regenerable",
          "Both functions are stated equations.",
          []),
    577: ("supporting",
          "Both inverse derivations (f(x)=10^(x+1) and g(x)=log_7(x+5)) are worked and verified fully in text; the graphs illustrate the stated function pairs.",
          "tikz_regenerable",
          "All four functions are stated equations.",
          []),
    578: ("decorative",
          "The model A=9,200 ln t+10,000 is given in the placeholder text and used directly in parts A-C; the airplane photo is scene-setting.",
          "irreplaceable_photo",
          "An airplane taking off is a real-world scene.",
          ["photo_solvable_from_text"]),
    579: ("supporting",
          "Per spec: students graph the stated functions y=ln x and y=log_(1/2) x on a blank grid; visual_type recorded as none despite has_visual=True.",
          "tikz_regenerable",
          "Blank coordinate grid for stated functions -- no source asset needed.",
          ["has_visual_true_but_visual_type_none", "needs_teacher_confirmation"]),
    589: ("essential",
          "'Are the logarithmic and exponential functions shown inverses of each other?' gives no equations for either function in the prompt text.",
          "source_pdf_required",
          "The two functions being compared exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    590: ("supporting",
          "The exponential function f(x)=5^(x+1) is stated explicitly, and each answer choice is a fully-written algebraic expression in the TABLE.",
          "tikz_regenerable",
          "f(x)=5^(x+1) is a stated function; the graph merely illustrates it.",
          []),
    592: ("decorative",
          "The function y=5 ln(x+1) is stated explicitly in the main text; the download-bar image is a UI illustration adding no new data.",
          "irreplaceable_photo",
          "A download progress-bar graphic tagged as a photo.",
          ["photo_solvable_from_text"]),
    593: ("supporting",
          "Both functions' value tables (g(x) and h(x)) are given completely in TABLE content for students to sketch from.",
          "tikz_regenerable",
          "The sketch is derivable directly from the given tables.",
          []),
    595: ("supporting",
          "The student's full (erroneous) work for inverting f(x)=5^(x-6)+2 is transcribed completely in the TABLE content, so the error is identifiable from text alone.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    597: ("essential",
          "'The graph shows a transformation of the parent graph f(x)=log_3 x. Write an equation for the graph' -- the specific shift/transformation is not stated anywhere in text.",
          "source_pdf_required",
          "The transformation shown must be read off the original figure.",
          ["needs_teacher_confirmation"]),
    598: ("supporting",
          "The function to graph, y=log_5 x, is fully stated; this is a blank-grid 'graph each function' task.",
          "tikz_regenerable",
          "Blank coordinate grid for a stated function.",
          []),
    599: ("supporting",
          "The function to graph, y=log_8 x, is fully stated; blank-grid task.",
          "tikz_regenerable",
          "Blank coordinate grid for a stated function.",
          []),
    600: ("supporting",
          "The function to graph, y=log_(3/10) x, is fully stated; blank-grid task.",
          "tikz_regenerable",
          "Blank coordinate grid for a stated function.",
          []),
    601: ("supporting",
          "The function to graph, y=log_0.1 x, is fully stated; blank-grid task.",
          "tikz_regenerable",
          "Blank coordinate grid for a stated function.",
          []),
    612: ("decorative",
          "The formula R=12 log(a+1)+25 is given in the placeholder text, matching the answer key's use of it; the coins/ad icons add no new data.",
          "irreplaceable_photo",
          "An icon/photo montage tagged as photo.",
          ["photo_solvable_from_text"]),
    613: ("supporting",
          "The model r=90-25 log(t+1) is stated explicitly and Part A's table of values is given in the answer key; the graph plots that stated function.",
          "tikz_regenerable",
          "r=90-25 log(t+1) is a stated function with tabulated points.",
          []),
    614: ("supporting",
          "The focus/epicenter/seismograph-station geometry (F, E, S, arc ES) is explained fully in prose, and Part A's numeric givens (A=700, T=2, D=100 deg) are all stated in text; the cutaway diagram illustrates the same relationships.",
          "tikz_regenerable",
          "A schematic cutaway of Earth with F, E, S, and arc ES labeled is a redrawable diagram despite being tagged photo.",
          ["needs_teacher_confirmation"]),
    624: ("supporting",
          "The key features (domain, range, intercept, asymptote, end behavior) of y=log x and y=10^x are both given completely in the TABLE; the graph cell illustrates the stated inverse-reflection relationship.",
          "tikz_regenerable",
          "Both functions are stated equations.",
          []),
    625: ("supporting",
          "Duplicate occurrence of the y=log x / y=10^x inverse-reflection concept summary.",
          "tikz_regenerable",
          "Both functions are stated equations.",
          []),
    633: ("supporting",
          "The transformation of f(x)=-log(x+3)-4 from the parent y=log x (shift left 3, reflect, down 4) is fully derived in text; the graph illustrates the stated function.",
          "tikz_regenerable",
          "f(x)=-log(x+3)-4 is a stated function.",
          []),

    # ---------------- 6-5 (11 rows) ----------------
    642: ("supporting",
          "The graph plots the stated function y=log x, and log 3, log 5, log 15 can be computed directly; the item reasons about a stated equation.",
          "tikz_regenerable",
          "y=log x is a simple stated logarithm.",
          []),
    643: ("supporting",
          "Duplicate occurrence of the y=log x Explore & Reason launch.",
          "tikz_regenerable",
          "y=log x is a simple stated logarithm.",
          []),
    647: ("supporting",
          "The acid-rain pH (4.5) needed to solve is captured in the reference chart's data (Acid rain pH=4.5), and the formula pH=log(1/[H+]) is given in text; the chart is a simple reference of four solutions' pH values.",
          "tikz_regenerable",
          "A small reference chart of four named solutions and their pH values -- fully specifiable and redrawable.",
          ["needs_teacher_confirmation"]),
    658: ("supporting",
          "Both stated functions y=log(1/x) and y=-log x are given in text; the graph is used to reason about why they coincide.",
          "tikz_regenerable",
          "Both functions are stated equations.",
          []),
    685: ("decorative",
          "The traffic intensity (I=10^-4 W/m^2) and headphone loudness (40 dB) needed for parts A-C are captured in the placeholder labels; the formula is given in the main text.",
          "irreplaceable_photo",
          "A street traffic scene and a person with headphones is a real-world photo.",
          ["photo_solvable_from_text"]),
    686: ("supporting",
          "The model A=2 log t+log5 is stated, and the week's daily high/low temperatures are given completely in the TABLE.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    687: ("supporting",
          "All five candidate expressions to check against log_2 3 are given completely in the TABLE.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    690: ("supporting",
          "The Product, Quotient, and Power properties of logarithms are stated completely in the TABLE.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    691: ("supporting",
          "Duplicate occurrence of the Product/Quotient/Power properties concept box.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    693: ("supporting",
          "Algebra, words, and numeric examples for all four logarithm properties (including change of base) are given completely in the TABLE.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    694: ("supporting",
          "Duplicate occurrence of the four logarithm properties concept summary.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),

    # ---------------- 4-4 (11 rows) ----------------
    725: ("decorative",
          "The math expression on the tablet (1/2+1/3+1/9) is identical to the expression already stated in the main prompt text.",
          "irreplaceable_photo",
          "A tablet screen photo, tagged as photo, not a redrawable technical figure.",
          ["photo_solvable_from_text"]),
    726: ("decorative",
          "Duplicate occurrence: the math expression on the tablet is identical to the expression already stated in the main prompt text.",
          "irreplaceable_photo",
          "A tablet/computer screen photo, tagged as photo, not a redrawable technical figure.",
          ["photo_solvable_from_text"]),
    731: ("decorative",
          "The train/car speed labels (r+15, r) shown in the image exactly match the rates already defined in the TABLE and algebra in the main text.",
          "irreplaceable_photo",
          "A commuter train and car photo is a real-world scene.",
          ["photo_solvable_from_text"]),
    749: ("essential",
          "'Find the perimeter of the quadrilateral in simplest form' -- no side lengths or expressions for the quadrilateral appear anywhere in the prompt text.",
          "source_pdf_required",
          "The quadrilateral's side-length expressions exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    752: ("essential",
          "'Find the slope of the line that passes through the points shown' -- no point coordinates appear anywhere in the prompt text.",
          "source_pdf_required",
          "The two points needed to compute slope exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    764: ("decorative",
          "All needed values (15-mile trail, 2 mph faster, 12 mph first-half speed) are already stated in the main prompt text; the image labels match.",
          "irreplaceable_photo",
          "A cyclist on a bike trail is a real-world scene.",
          ["photo_solvable_from_text"]),
    769: ("decorative",
          "All needed values (5 mi downstream at 3 mph faster than current, 4 mi upstream at 1 mph slower) are stated in the main prompt text.",
          "irreplaceable_photo",
          "A person paddling a kayak is a real-world scene.",
          ["photo_solvable_from_text"]),
    770: ("essential",
          "'The resistance of electrical circuits A and B are shown' -- no resistance values or circuit diagrams appear in the prompt text.",
          "source_pdf_required",
          "Circuit A/B component values exist only in the original figure.",
          ["needs_teacher_confirmation"]),
    774: ("supporting",
          "The lens equation and all its variables (f, d_i, d_o) are defined completely in the main prompt text; the diagram merely labels the same variables on a schematic lens setup.",
          "tikz_regenerable",
          "A labeled optical schematic (object, lens, image screen, f, d_o, d_i) with every symbol already defined in text.",
          []),
    787: ("supporting",
          "Both the common-denominator and different-denominator addition/subtraction rules are demonstrated fully in the TABLE with worked numeric and algebraic examples.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    788: ("essential",
          "Items 1-10 are fully self-contained text, but the closing item 11 ('Find the perimeter of the quadrilateral in simplest form') repeats the same undimensioned quadrilateral figure as 4-4-savvas-q11, with no side lengths given in text.",
          "source_pdf_required",
          "The quadrilateral's dimensions for item 11 exist only in the original figure, same gap as 4-4-savvas-q11.",
          ["needs_teacher_confirmation"]),

    # ---------------- 4-5 (14 rows) ----------------
    816: ("supporting",
          "Both Nicky's and Tavon's complete step-by-step methods for solving (1/2)x+(2/5)=(9/10) are transcribed fully into the TABLE.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    817: ("supporting",
          "Duplicate occurrence of the Nicky/Tavon method-comparison table.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    819: ("decorative",
          "'Cheyenne is twice as fast' is repeated in the worked solution text itself (Step 1), and the 24-hour combined time is in the main prompt.",
          "irreplaceable_photo",
          "Two people making paper-cutting designs is a real-world scene.",
          ["photo_solvable_from_text"]),
    820: ("supporting",
          "The full algebraic solution (x=5 extraneous, x=-1 valid) is worked in text; the graph of the two stated functions confirms the single intersection.",
          "tikz_regenerable",
          "f(x)=1/(x-5)+x/(x-3) and g(x)=2/(x^2-8x+15) are stated functions.",
          []),
    822: ("decorative",
          "All needed values (16 mi downstream, 6 mi upstream, 1 hr longer upstream, 5 mph still-water rate) are stated in the main prompt text.",
          "irreplaceable_photo",
          "A person paddling a canoe is a real-world scene.",
          ["photo_solvable_from_text"]),
    834: ("decorative",
          "The river current (4 km/h) needed to solve is captured in the image label, and the 6 km/12 km distances are in the main text.",
          "irreplaceable_photo",
          "A boat on a river is a real-world scene.",
          ["needs_teacher_confirmation", "photo_solvable_from_text"]),
    846: ("decorative",
          "Both workers' individual completion times (Malia 4 hours, Paige 6 hours) needed to solve are captured in the image labels.",
          "irreplaceable_photo",
          "A landscaping crew photo is a real-world scene.",
          ["photo_solvable_from_text"]),
    847: ("decorative",
          "The combined completion time (8 hours) needed to solve is captured in the image label; 'three times as fast' is in the main text.",
          "irreplaceable_photo",
          "Two people building a shed is a real-world scene.",
          ["photo_solvable_from_text"]),
    853: ("decorative",
          "All needed values (1,500 mi with wind, 1,000 mi against wind, 550 mph still-air speed) are stated in the main prompt text.",
          "irreplaceable_photo",
          "A commercial jet photo is a real-world scene.",
          ["photo_solvable_from_text"]),
    854: ("decorative",
          "Duplicate occurrence: all needed values are stated in the main prompt text.",
          "irreplaceable_photo",
          "A commercial jet/windsock photo is a real-world scene.",
          ["photo_solvable_from_text"]),
    858: ("supporting",
          "All five candidate rational equations to check for extraneous solutions are given completely in the TABLE.",
          "tikz_regenerable",
          "Fully specified TABLE content.",
          []),
    859: ("decorative",
          "The function f(x)=(50(0.02)+x(0.06))/(50+x) and all given percentages/volumes (6%, 50 gal, 2%) are stated in the main prompt text; the image repeats the same labels.",
          "irreplaceable_photo",
          "A chemist pouring liquid is a real-world scene.",
          ["photo_solvable_from_text"]),
    860: ("decorative",
          "Duplicate occurrence: the function and all given percentages/volumes are stated in the main prompt text.",
          "irreplaceable_photo",
          "A chemist pouring liquid is a real-world scene.",
          ["photo_solvable_from_text"]),
    866: ("supporting",
          "Per spec, this is the mislabeled map row -- a concept-summary table (algebra worked fully in text) plus a closing text-only word problem restating the same 6 km/12 km/4 km/h boat scenario already resolvable from its own text.",
          "tikz_regenerable",
          "Concept-summary TABLE content plus a fully-specified boat word problem.",
          ["visual_type_map_is_concept_summary"]),
}
